### ISSUE TITLE
Move WordPress theme files to a subdir

### ISSUE THREAD

**Issue by szepeviktor** [claytoncollie/rosenfield-collection-theme-2020#2]
Move

- functions.php
- screenshot.png
- single.php
- style.css 

to `theme/` de-cluttering root.

Please see https://github.com/timber/starter-theme/tree/2.x

WordPress core automatically discovers that directory.

**Comment by claytoncollie** [comment]
@szepeviktor Are you on correct repository Viktor? @

**Comment by szepeviktor** [comment]
Yes, Timber is only an example.

**Comment by claytoncollie** [comment]
This is a client project and I will not be accepting any outsides changes.

**Comment by szepeviktor** [comment]
This is just an issue to make this client project better.
